name: neurotrader
channels:
  - conda-forge
  - anaconda
dependencies:
  # --- Conda Packages ---
  - python=3.11
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - xgboost
  - pandas-ta
  - python-dotenv
  - numpy<2.0
  - pip
  - libuv

  # Web and Database
  - django
  - psycopg2

  # --- Pip Packages for XPU ---
  - pip:
    - torch==2.5.1+cxx11.abi
    - torchvision==0.20.1+cxx11.abi
    - torchaudio==2.5.1+cxx11.abi
    - intel-extension-for-pytorch==2.5.10+xpu
