name: neurotrader
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - notebook
  - pandas
  - matplotlib
  - alpha_vantage
  - python-dotenv
  - numpy<2.0
  - xgboost
  - scikit-learn
  - pandas-ta